Add MIRROR_TOKEN availability check in workflow
Added a test for MIRROR_TOKEN availability before mirroring the repository.

Signed-off-by: Gabriele Galletta <43389006+Daddi14@users.noreply.github.com>

diff --git a/.github/workflows/mirror.yml b/.github/workflows/mirror.yml
--- a/.github/workflows/mirror.yml
+++ b/.github/workflows/mirror.yml
@@ -16,10 +16,24 @@ jobs:
         uses: actions/checkout@v5
         with:
           fetch-depth: 0
-      - name: Check authentication
+
+      - name: Test mirror authentication
+        env:
+          MIRROR_TOKEN: ${{ secrets.MIRROR_TOKEN }}
         run: |
-          git ls-remote https://x-access-token:${{ secrets.MIRROR_TOKEN }}@github.com/EXOPA-OAPa/photo-cat.git
+          if [ -z "$MIRROR_TOKEN" ]; then
+            echo "ERROR: MIRROR_TOKEN is empty or unavailable"
+            exit 1
+          fi
+
+          echo "MIRROR_TOKEN is available"
+
+          git ls-remote \
+            "https://x-access-token:${MIRROR_TOKEN}@github.com/EXOPA-OAPa/photo-cat.git"
 
       - name: Mirror repository
+        env:
+          MIRROR_TOKEN: ${{ secrets.MIRROR_TOKEN }}
         run: |
-          git push --mirror https://x-access-token:${{ secrets.MIRROR_TOKEN }}@github.com/EXOPA-OAPa/photo-cat.git
+          git push --mirror \
+            "https://x-access-token:${MIRROR_TOKEN}@github.com/EXOPA-OAPa/photo-cat.git"
